// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzh_K1MNo4wklyqLWxOI243LE0FPU1fWY',
    appId: '1:983779435621:web:53cf6ed09ca1ddeaab528c',
    messagingSenderId: '983779435621',
    projectId: 'fb-app-2a1b1',
    authDomain: 'fb-app-2a1b1.firebaseapp.com',
    storageBucket: 'fb-app-2a1b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9_PduWqH2JPq9P8SND5pnXMp8sRSkyQ',
    appId: '1:983779435621:android:0546a8846f0251cbab528c',
    messagingSenderId: '983779435621',
    projectId: 'fb-app-2a1b1',
    storageBucket: 'fb-app-2a1b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT_A7AOj2nro-9jkyDWi4u-kDRm9PNwEo',
    appId: '1:983779435621:ios:8f55e3f74e4c8c5bab528c',
    messagingSenderId: '983779435621',
    projectId: 'fb-app-2a1b1',
    storageBucket: 'fb-app-2a1b1.appspot.com',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT_A7AOj2nro-9jkyDWi4u-kDRm9PNwEo',
    appId: '1:983779435621:ios:8f55e3f74e4c8c5bab528c',
    messagingSenderId: '983779435621',
    projectId: 'fb-app-2a1b1',
    storageBucket: 'fb-app-2a1b1.appspot.com',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzh_K1MNo4wklyqLWxOI243LE0FPU1fWY',
    appId: '1:983779435621:web:0abc24f702e3f8d1ab528c',
    messagingSenderId: '983779435621',
    projectId: 'fb-app-2a1b1',
    authDomain: 'fb-app-2a1b1.firebaseapp.com',
    storageBucket: 'fb-app-2a1b1.appspot.com',
  );
}
